# 1 Data Set

The data set consists of three types of entities: 
* the specification of an auto in terms of various characteristics;
* its assigned insurance risk rating;
* its normalized losses in use as compared to other cars.

# 2 Import Data

Upload the dataset of Cars.data.

In [0]:
from google.colab import files
uploaded = files.upload()

Import the dataset into a data frame named **cars**. The dataframe shows that the data set consists of 205 rows and 26 columns without a header.

In [0]:
import pandas as pd
from pandas import DataFrame
cars = pd.read_csv('Cars.data', header = None)
cars

# 3 Name Attributes

Name the attributes for each column.

In [0]:
cars.columns = ['symboling','normalized-losses','make','fuel-type','aspiration','num-of-doors','body-style','drive-wheels','engine-location','wheel-base','length','width','height','curb-weight','engine-type','num-of-cylinders','engine-size','fuel-system','bore','stroke','compression-ratio','horsepower','peak-rpm','city-mpg','highway-mpg','price']
cars.head(5)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

1. symboling: -3, -2, -1, 0, 1, 2, 3. 
2. normalized-losses: continuous from 65 to 256. 
3. make: alfa-romero, audi, bmw, chevrolet, dodge, honda,isuzu, jaguar, mazda, mercedes-benz, mercury, mitsubishi, nissan, peugot, plymouth, porsche, renault, saab, subaru, toyota, volkswagen, volvo 
4. fuel-type: diesel, gas. 
5. aspiration: std, turbo. 
6. num-of-doors: four, two. 
7. body-style: hardtop, wagon, sedan, hatchback, convertible. 
8. drive-wheels: 4wd, fwd, rwd. 
9. engine-location: front, rear. 
10. wheel-base: continuous from 86.6 120.9. 
11. length: continuous from 141.1 to 208.1. 
12. width: continuous from 60.3 to 72.3. 
13. height: continuous from 47.8 to 59.8. 
14. curb-weight: continuous from 1488 to 4066. 
15. engine-type: dohc, dohcv, l, ohc, ohcf, ohcv, rotor. 
16. num-of-cylinders: eight, five, four, six, three, twelve, two. 
17. engine-size: continuous from 61 to 326. 
18. fuel-system: 1bbl, 2bbl, 4bbl, idi, mfi, mpfi, spdi, spfi. 
19. bore: continuous from 2.54 to 3.94. 
20. stroke: continuous from 2.07 to 4.17. 
21. compression-ratio: continuous from 7 to 23. 
22. horsepower: continuous from 48 to 288. 
23. peak-rpm: continuous from 4150 to 6600. 
24. city-mpg: continuous from 13 to 49. 
25. highway-mpg: continuous from 16 to 54. 
26. price: continuous from 5118 to 45400.

# 4 Filter Data

The data frame shows 15 columns with continuous values and 10 columns with discrete values.

Discrete values provides limited options for analysis, with low sensitivity outcomes and little indication of sources of variation. Continuous values provides variety of analysis options that can offer high sensitivity outcomes and insight into the sources of variation.

Therefore, select only the columns with continuous values and import into a new data frame named **numeric_cars**.

In [0]:
numeric_cars = cars.filter(['normalized-losses','wheel-base','length','width','height','curb-weight','engine-size','bore','stroke','compression-ratio','horsepower','peak-rpm','city-mpg','highway-mpg','price'], axis=1)
numeric_cars.head(5)

,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,?,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111,5000,21,27,13495
1,?,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111,5000,21,27,16500
2,?,94.5,171.2,65.5,52.4,2823,152,2.68,3.47,9.0,154,5000,19,26,16500
3,164,99.8,176.6,66.2,54.3,2337,109,3.19,3.40,10.0,102,5500,24,30,13950
4,164,99.4,176.6,66.4,54.3,2824,136,3.19,3.40,8.0,115,5500,18,22,17450

# 5 Data Cleaning

There are missing values with the string "?" which needs to be replaced with "NaN in the **numeric_cars** data.

It means "not a number", a value that you get if you perform a calculation whose result can't be expressed as a number. Any calculations you perform with "NaN" will also result in "NaN".

In [0]:
import numpy as np
numeric_cars = numeric_cars.replace('?', np.NaN)
numeric_cars.head(5)

,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,NaN,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111,5000,21,27,13495
1,NaN,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111,5000,21,27,16500
2,NaN,94.5,171.2,65.5,52.4,2823,152,2.68,3.47,9.0,154,5000,19,26,16500
3,164,99.8,176.6,66.2,54.3,2337,109,3.19,3.40,10.0,102,5500,24,30,13950
4,164,99.4,176.6,66.4,54.3,2824,136,3.19,3.40,8.0,115,5500,18,22,17450

Upon checking the data type of the attributes in **numeric_cars**, we see that it has a mix of object, float and integer data types. 

It is advisable to convert these data types to a single data type as we might have to reference a data type in a variable of another type.

In [0]:
numeric_cars.dtypes

normalized-losses     object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-size            int64
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                 object
dtype: object

Convert the data types of attributes in **numeric_cars** to "float".

In [0]:
numeric_cars = numeric_cars.apply(pd.to_numeric, downcast = 'float', errors = 'coerce')
numeric_cars.dtypes

normalized-losses    float32
wheel-base           float32
length               float32
width                float32
height               float32
curb-weight          float32
engine-size          float32
bore                 float32
stroke               float32
compression-ratio    float32
horsepower           float32
peak-rpm             float32
city-mpg             float32
highway-mpg          float32
price                float32
dtype: object

Report the number of null values "NaN" for each attribute (column).

In [0]:
len(numeric_cars) - numeric_cars.count()

normalized-losses    41
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-size           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64

Since 'price' is the column used for prediction and it has 4 rows with missing 'price' values, remove them entirely and again report the number of missing values "NaN" for each column.

In [0]:
numeric_cars = numeric_cars[np.isfinite(numeric_cars['price'])]
len(numeric_cars) - numeric_cars.count()

normalized-losses    37
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-size           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 0
dtype: int64

Find column mean for each column.

In [0]:
numeric_cars.mean()

normalized-losses      122.000000
wheel-base              98.797112
length                 174.200943
width                   65.889053
height                  53.766693
curb-weight           2555.666748
engine-size            126.875626
bore                     3.330711
stroke                   3.256906
compression-ratio       10.164281
horsepower             103.396988
peak-rpm              5117.587891
city-mpg                25.179104
highway-mpg             30.686567
price                13207.128906
dtype: float32

Replace missing values "NaN" in other columns using column means.

In [0]:
numeric_cars = numeric_cars.fillna(numeric_cars.mean())
numeric_cars.head(5)

,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,122.0,88.599998,168.800003,64.099998,48.799999,2548.0,130.0,3.47,2.68,9.0,111.0,5000.0,21.0,27.0,13495.0
1,122.0,88.599998,168.800003,64.099998,48.799999,2548.0,130.0,3.47,2.68,9.0,111.0,5000.0,21.0,27.0,16500.0
2,122.0,94.500000,171.199997,65.500000,52.400002,2823.0,152.0,2.68,3.47,9.0,154.0,5000.0,19.0,26.0,16500.0
3,164.0,99.800003,176.600006,66.199997,54.299999,2337.0,109.0,3.19,3.40,10.0,102.0,5500.0,24.0,30.0,13950.0
4,164.0,99.400002,176.600006,66.400002,54.299999,2824.0,136.0,3.19,3.40,8.0,115.0,5500.0,18.0,22.0,17450.0

Ensure that there's no more missing values "NaN"

In [0]:
len(numeric_cars) - numeric_cars.count()

normalized-losses    0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-size          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

We will be using the k-nearest neighbors algorithm to determine the prices of the car. The k-nearest neighbors algorithm uses the euclidean distance to determine the closest neighbor.

However in **numeric_cars**, each column has a different scaling. For example, if we take row 2 and row 3, the 'peak-rpm' has a difference of 500, while the difference in 'width' is 0.7. The algorithm in this case will give extra weight towards the difference in 'peak-rpm'.

Therefore, it is important to normalize the dataset into a unit vector with values ranging from 0 to 1.

Minimum - Maximum Normalization:

$z_i=(x_i-min(x))/(max(x)-min(x))$  
where $x=(x_1,x_2,\cdots,x_n)$ and $z_i$ is now your $i_{th}$ normalised data.

Normalise all columnns to range from 0 to 1 except for the target column 'price' as it will be used for prediction.

In [0]:
norm_cars=((numeric_cars-numeric_cars.min())/(numeric_cars.max()-numeric_cars.min()))*1
norm_cars["price"]=numeric_cars["price"]
norm_cars.head(5)

,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,0.298429,0.058309,0.413433,0.324786,0.083333,0.411171,0.260377,0.664286,0.290476,0.1250,0.294393,0.346939,0.222222,0.289474,13495.0
1,0.298429,0.058309,0.413433,0.324786,0.083333,0.411171,0.260377,0.664286,0.290476,0.1250,0.294393,0.346939,0.222222,0.289474,16500.0
2,0.298429,0.230321,0.449254,0.444444,0.383334,0.517843,0.343396,0.100000,0.666667,0.1250,0.495327,0.346939,0.166667,0.263158,16500.0
3,0.518325,0.384840,0.529851,0.504273,0.541667,0.329325,0.181132,0.464286,0.633333,0.1875,0.252336,0.551020,0.305556,0.368421,13950.0
4,0.518325,0.373178,0.529851,0.521368,0.541667,0.518231,0.283019,0.464286,0.633333,0.0625,0.313084,0.551020,0.138889,0.157895,17450.0

# 6 Univariate Model [KNeighborsRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsRegressor.html) with Fixed k Value

Since we are predicting the price of cars, we should use **KNeighborsRegressor** rather than **KNeighborsClassifier**. 

Before we apply **KNeighborsRegressor**, use **train_test_split** function to randomise the order of rows and split the data into training set (80%) and test set (20%) with the random seed as 1.

Fit a KNN model using default k value **KNeighborsRegressor()**.

For each column except `price`, train a model, return RMSE value and add to the dictionary `rmse_results`.

In [0]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error

train_cols = norm_cars.columns.drop('price')
X = norm_cars[train_cols]
y = norm_cars['price']
rmse_results = {}

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

for i in X:
  adj = KNeighborsRegressor()
  adj.fit(X_train[[i]], y_train)
  forecasts = adj.predict(X_test[[i]])
  rmse_results[i] = np.sqrt(mean_squared_error(y_test, forecasts))

In [0]:
rmse_results

{'bore': 6430.009,
 'city-mpg': 3524.5251,
 'compression-ratio': 7120.226,
 'curb-weight': 3255.2756,
 'engine-size': 3384.7676,
 'height': 6958.8726,
 'highway-mpg': 4007.365,
 'horsepower': 3221.8066,
 'length': 3653.4937,
 'normalized-losses': 6577.6973,
 'peak-rpm': 6208.026,
 'stroke': 6045.587,
 'wheel-base': 5209.8896,
 'width': 3674.956}

# 7 Outcomes

Report the rmse_results in an ascending order.

In [0]:
for s in sorted(rmse_results, key=rmse_results.get):
         print(s,'', rmse_results[s])

horsepower  3221.8066
curb-weight  3255.2756
engine-size  3384.7676
city-mpg  3524.5251
length  3653.4937
width  3674.956
highway-mpg  4007.365
wheel-base  5209.8896
stroke  6045.587
peak-rpm  6208.026
bore  6430.009
normalized-losses  6577.6973
height  6958.8726
compression-ratio  7120.226

Good predictors will point to lower RMSE values and 'horsepower' seems to be the best predictor with the lowest RMSE value, closer to the actual price.

'compression-ratio' seems to be the worst predictor with highest RMSE value, far from the actual price.